export const SET_UPLOAD_FILE = 'SET_UPLOAD_FILE';
export const SET_UPLOAD_FILE_PATH = 'SET_UPLOAD_FILE_PATH';
export const SET_INFORMATION = 'SET_INFORMATION';

export const SET_IMPORT_OBJECT = 'SET_IMPORT_OBJECT';